// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    title, body
) VALUES (
    $1, $2
)
RETURNING id, title, created_at
`

type CreatePostParams struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type CreatePostRow struct {
	ID        int64              `json:"id"`
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (CreatePostRow, error) {
	row := q.db.QueryRow(ctx, createPost, arg.Title, arg.Body)
	var i CreatePostRow
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}
